/**                                                                     
 *  /file guwhiteboardtypelist_c_typestrings_generated.c                
 *                                                                      
 *  Created by Carl Lusty in 2013.                                      
 *  Copyright (c) 2013 Carl Lusty                                       
 *  All rights reserved.                                                
 */                                                                     

#include "gusimplewhiteboard.h"
#include "guwhiteboardtypelist_c_generated.h"

//Generated on: Wed Jan 20 00:03:35 2016
//Generated by user: nap

const char *WBTypes_stringValues[] = 
{
        "*",
        "Print",
        "Say",
        "Speech",
        "QSay",
        "QSpeech",
        "SpeechOutput",
        "fsm_control",
        "fsm_status",
        "fsm_names",
        "fsm_states",
        "EPuckAccel_Control",
        "EPuckAccel_Status",
        "EPuckCamera_Control",
        "EPuckCamera_Status",
        "EPuckGSM_Control",
        "EPuckGSM_Status",
        "EPuckLight_Control",
        "EPuckLight_Status",
        "EPuckProximity_Control",
        "EPuckProximity_Status",
        "DifferentialRobotControl",
        "DifferentialRobotStatus",
        "EPuckLED_Control",
        "EPuckLED_Status",
        "GOAL_Control",
        "GOAL_Status",
        "Intersection_Status",
        "Direction_Control",
        "Obstacle_On_Path",
        "Angle",
        "Obstacle",
        "Current_Position",
        "Plan_Planner_Settings",
        "Plan_Domain_Filename",
        "Plan_Problem_Filename",
        "Plan_Obstacles_Filename",
        "Plan_Plan_Filename",
        "Manager_Status",
        "Planner_Status",
        "Plan_Goal_List",
        "Plan_Obstacle_List",
        "Epuck_Test_Control",
        "Epuck_Test_Status",
        "Epuck_Test_Start_Up"
};      

